In [ ]:
import numpy as np
import pandas as pd

# Q1 Create a 3×3 numpy array of all True’s

In [ ]:
# Q1
a1 = np.array([[True,True,True],[True,True,True],[True,True,True]])

In [ ]:
a1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a2 = np.ones((3,3),dtype=bool)

In [ ]:
a2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a3 = np.arange(9).reshape(3,3).astype('b')

In [ ]:
a3 # Not changing into boolean value

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int8)

# Q2 Extract all odd numbers from arrays
Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Output: array([1, 3, 5, 7, 9])


In [ ]:
b1 = np.arange(1,10,2)

In [ ]:
b1

array([1, 3, 5, 7, 9])

In [ ]:
b2 = np.arange(10)

In [ ]:
b2[b2%2!=0]

array([1, 3, 5, 7, 9])

# Q3 Replace all even numbers in above array with -5


In [ ]:
c1 = np.arange(10)

In [ ]:
c1[c1%2==0] = -5

In [ ]:
c1

array([-5,  1, -5,  3, -5,  5, -5,  7, -5,  9])

# Q4 Reshape an array
Input: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Output: array([[0, 1, 2, 3, 4],
       		[5, 6, 7, 8, 9]])

In [ ]:
d1 = np.arange(10).reshape(2,5)

In [ ]:
d1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Q5 How to get the positions where elements of two arrays match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

output = (array([1, 3, 5, 7]),)

In [ ]:
e1 = np.random.randint(10,size = (10))

In [ ]:
e1

array([1, 8, 0, 8, 6, 7, 4, 6, 1, 3])

In [ ]:
e2 = np.random.randint(10,size = (10))

In [ ]:
e2

array([6, 9, 5, 4, 6, 8, 4, 5, 4, 4])

In [ ]:
np.where(e1==e2)

(array([4, 6]),)

# Q6 Swap columns 1 and 2 in the array
Input: np.array [[1,2,3],[4,5,6],[7,8,9]]
Output: array([[2, 1, 3], [5, 4, 6], [8, 7, 9]])


In [ ]:
f1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
f1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
f1[:,[1,0,2]]

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

# Q7 Reversing the columns of a 2D array
Input: np.array [[1,2,3],[4,5,6],[7,8,9]]
Output:
array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])


In [ ]:
g1 = np.arange(1,10).reshape(3,3)

In [ ]:
g1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
g1[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

# Q8 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [ ]:
h1 = np.linspace(5,10,15).reshape(5,3)

In [ ]:
h1

array([[ 5.        ,  5.35714286,  5.71428571],
       [ 6.07142857,  6.42857143,  6.78571429],
       [ 7.14285714,  7.5       ,  7.85714286],
       [ 8.21428571,  8.57142857,  8.92857143],
       [ 9.28571429,  9.64285714, 10.        ]])

In [ ]:
h2 = np.random.uniform(5,10,size=(5,3))

In [ ]:
h2

array([[9.57202446, 8.60794713, 5.65841875],
       [7.82700859, 9.37264552, 5.74429956],
       [8.72683087, 5.22091224, 7.72363659],
       [7.71459893, 5.80299467, 6.0945786 ],
       [5.0206374 , 6.57444769, 8.01691356]])

# Q9 Create a 2d array with 1 on the border and 0 inside 

In [ ]:
i1 = np.ones((8,9))

In [ ]:
i1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
i1[1:-1,1:-1] = 0

In [ ]:
i1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Q10 If X = array([[ 9,   1,  12,  3],
          [ 14,  15,  6,  7],
          [ 18,  9,  10, 11]])

Expected output: array([12, 14, 11])
Write script to produce the desired output. Use of fancy indexing is must. 

In [ ]:
j1 = np.array([[ 9,   1,  12,  3],
          [ 14,  15,  6,  7],
          [ 18,  9,  10, 11]])

In [ ]:
j1

array([[ 9,  1, 12,  3],
       [14, 15,  6,  7],
       [18,  9, 10, 11]])

In [ ]:
row = np.array([0,1,2])
col = np.array([2,0,3])

In [ ]:
j1[row,col]

array([12, 14, 11])