In [1]:
import numpy as np
import pandas as pd

# Q1 Create a 3×3 numpy array of all True’s

In [2]:
# Q1
a1 = np.array([[True, True, True], [True, True, True], [True, True, True]])


In [3]:
a1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
a2 = np.ones((3, 3), dtype=bool)


In [5]:
a2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
a3 = np.arange(9).reshape(3, 3).astype("b")


In [7]:
a3  # Not changing into boolean value


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int8)

# Q2 Extract all odd numbers from arrays
Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Output: array([1, 3, 5, 7, 9])


In [8]:
b1 = np.arange(1, 10, 2)


In [9]:
b1

array([1, 3, 5, 7, 9])

In [10]:
b2 = np.arange(10)

In [11]:
b2[b2 % 2 != 0]


array([1, 3, 5, 7, 9])

# Q3 Replace all even numbers in above array with -5


In [12]:
c1 = np.arange(10)

In [13]:
c1[c1 % 2 == 0] = -5


In [14]:
c1

array([-5,  1, -5,  3, -5,  5, -5,  7, -5,  9])

# Q4 Reshape an array
Input: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Output: array([[0, 1, 2, 3, 4],
       		[5, 6, 7, 8, 9]])

In [15]:
d1 = np.arange(10).reshape(2, 5)


In [16]:
d1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Q5 How to get the positions where elements of two arrays match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

output = (array([1, 3, 5, 7]),)

In [17]:
e1 = np.random.randint(10, size=(10))


In [18]:
e1

array([1, 6, 9, 0, 2, 3, 3, 7, 6, 9])

In [19]:
e2 = np.random.randint(10, size=(10))


In [20]:
e2

array([8, 8, 4, 1, 6, 5, 3, 1, 3, 3])

In [21]:
np.where(e1 == e2)


(array([6], dtype=int64),)

# Q6 Swap columns 1 and 2 in the array
Input: np.array [[1,2,3],[4,5,6],[7,8,9]]
Output: array([[2, 1, 3], [5, 4, 6], [8, 7, 9]])


In [22]:
f1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [23]:
f1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
f1[:, [1, 0, 2]]


array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

# Q7 Reversing the columns of a 2D array
Input: np.array [[1,2,3],[4,5,6],[7,8,9]]
Output:
array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])


In [25]:
g1 = np.arange(1, 10).reshape(3, 3)


In [26]:
g1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
g1[:, ::-1]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

# Q8 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [28]:
h1 = np.linspace(5, 10, 15).reshape(5, 3)


In [29]:
h1

array([[ 5.        ,  5.35714286,  5.71428571],
       [ 6.07142857,  6.42857143,  6.78571429],
       [ 7.14285714,  7.5       ,  7.85714286],
       [ 8.21428571,  8.57142857,  8.92857143],
       [ 9.28571429,  9.64285714, 10.        ]])

In [30]:
h2 = np.random.uniform(5, 10, size=(5, 3))


In [31]:
h2

array([[6.80202332, 9.26877664, 7.41598961],
       [8.37892034, 9.31725346, 7.78699939],
       [8.6150975 , 8.40513207, 7.97932677],
       [7.21007967, 8.25638999, 5.73752546],
       [9.58117507, 6.80573348, 8.94910684]])

# Q9 Create a 2d array with 1 on the border and 0 inside 

In [32]:
i1 = np.ones((8, 9))


In [33]:
i1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
i1[1:-1, 1:-1] = 0


In [35]:
i1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Q10 If X = array([[ 9,   1,  12,  3],
          [ 14,  15,  6,  7],
          [ 18,  9,  10, 11]])

Expected output: array([12, 14, 11])
Write script to produce the desired output. Use of fancy indexing is must. 

In [36]:
j1 = np.array([[9, 1, 12, 3], [14, 15, 6, 7], [18, 9, 10, 11]])


In [37]:
j1

array([[ 9,  1, 12,  3],
       [14, 15,  6,  7],
       [18,  9, 10, 11]])

In [38]:
row = np.array([0, 1, 2])
col = np.array([2, 0, 3])


In [39]:
j1[row, col]


array([12, 14, 11])